CC=gcc

all:
	$(CC) 1.c -o ques1 
	$(CC) 2_singlelist.c -o ques2_singlelist
	$(CC) 2_doublelist.c -o ques2_doublelist
	$(CC) 2_stack.c -o ques2_stack
	$(CC) 2_queue.c -o ques2_queue
	$(CC) 4.c -o ques4 
	$(CC) 5.c -o ques5 

q1: 1.c
	$(CC) 1.c -o ques1 
	.\ques1

q2: 2.c
	$(CC) 2_singlelist.c -o ques2_singlelist
	$(CC) 2_doublelist.c -o ques2_doublelist
	$(CC) 2_stack.c -o ques2_stack
	$(CC) 2_queue.c -o ques2_queue
	./ques2_singlelist
	./ques2_doublelist
	./ques2_stack
	./ques2_queue

q4: 4.c
	$(CC) 4.c -o ques4
	./ques4

q5: 5.c
	$(CC) 5.c -o ques5
	./ques5