CC=gcc

all:
	$(CC) 1.c -o ques1 
	$(CC) 2.c -o ques2 
	$(CC) 3.c -o ques3 
	$(CC) 4.c -o ques4 
	$(CC) 5.c -o ques5 

q1: 1.c
	$(CC) 1.c -o ques1 
	./ques1

q2: 2.c
	$(CC) 2.c -o ques2
	./ques2

q3: 3.c
	$(CC) 3.c -o ques3 
	./ques3

q4: 4.c
	$(CC) 4.c -o ques4
	./ques4

q5: 5.c
	$(CC) 5.c -o ques5
	./ques5