CC=gcc

all:
	$(CC) 3_avl.c -o ques3_avl
	$(CC) 3_bst.c -o ques3_bst
	$(CC) 4.c -o ques4


q3: 3.c
	$(CC) 3_avl.c -o ques3_avl
	$(CC) 3_bst.c -o ques3_bst
	./ques3_avl
	./ques3_bst

q4: 4.c
	$(CC) 4.c -o ques4
	./ques4
